version: "3.1"

services:

  mongo:
    container_name: mongo-db
    image: mongo
    networks: 
      - crud-web-app-network
    ports:
      - 27017:27017  
  
  mongo-express:
    container_name: mongo-exp
    image: mongo-express
    networks: 
      - crud-web-app-network
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: 'true'
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_URL: mongodb://mongo:27017/
  
  web-app:
    container_name: web-app
    build: .
    networks: 
      - crud-web-app-network
    ports:
      - 8080:8080

networks:
  crud-web-app-network:
    driver: bridge    